### ISSUE TITLE
Units - no respond

### ISSUE THREAD

**Issue by Sal-coding-in-progress** [dploeger/sketch-plugin-units#13]
When I clicked any of the functions, none responded.

**Comment by dploeger** [comment]
Which versions of Sketch and the plugin are you using?

**Comment by Sal-coding-in-progress** [comment]
Sketch version: 48.2
Plugin: 2.0.0-rc.1

**Comment by dploeger** [comment]
Can you try updating to 2.0.0 (https://github.com/dploeger/sketch-plugin-units/releases/tag/v2.0.0)

**Comment by Sal-coding-in-progress** [comment]
I think that's the same version, I downloaded the plugin from your link, and re-installed it, still the same.

**Comment by dploeger** [comment]
Oh, right. The version's wrong in 2.0.0. Bummer.

I just saw, that your version of Sketch is more than three years old. Older than this repository. I guess, that's way too old for this plugin (it uses HTMLView for the dialogs so maybe that wasn't there three years ago)

Please try updating to a more current version of Sketch. I'm on 70.6 now and can't reproduce the problem.

**Comment by Sal-coding-in-progress** [comment]
Oh ok, I see. It seems because of my Mac system version, Sketch 48.2 is the newest version I could get, so I guess I will give it another try once I figure out how to update my Mac. Thank you!

**Comment by dploeger** [comment]
You're welcome. Good luck!
