### ISSUE TITLE
No windows appear

### ISSUE THREAD

**Issue by smdjeff** [dploeger/sketch-plugin-units#19]
Using Sketch 51.3 and installed with a double click from here.
https://github.com/dploeger/sketch-plugin-units/releases/tag/v2.0.0

I've seen this plugin work on my other machine, but even after a reboot, nothing.

Also tried the release candidates, they also didn't work./

Interesting, 1.0.0 does seem to work!

**Comment by dploeger** [comment]
Hm... I don't know if v2.0.0 supports Sketch 51, which is *very* old. :)

Can you try using a more current version? I can't reproduce the problem with the most current version at least.
