### ISSUE TITLE
resize window does no appear when i click

### ISSUE THREAD

**Issue by becks1990** [dploeger/sketch-plugin-units#20]
resize window does no appear when i click, i have sketch Version 73.1

**Comment by dploeger** [comment]
Hm. I can't reproduce that here in 73.1. Does the settings window appear?

**Comment by becks1990** [comment]
yes, setting window appear and also the show size window

**Comment by dploeger** [comment]
That's weird. They all use the same way of displaying things. What type of layer did you select before you clicked resize?

**Comment by becks1990** [comment]
A rectangle

**Comment by dploeger** [comment]
Can you run Sketch from a terminal like this please:

```
/Applications/Sketch.app/Contents/MacOS/Sketch
```

It should show you some logs. See if there's any error coming up.

**Comment by becks1990** [comment]
it works now :)
thanks !

**Comment by dploeger** [comment]
Ha. Typical case of "using logging to make a bug vanish" 🤣

**Comment by becks1990** [comment]
haha yes !! 👏
