### ISSUE TITLE
Crashes Sketch Version 84 (140208)

### ISSUE THREAD

**Issue by syky27** [dploeger/sketch-plugin-units#22]
Crashes immediately after pressing menu item 'Units' -> 'Resize'

I can send you logs if you tell me where to find them...

**Comment by dploeger** [comment]
I'm on Sketch 89 now and it still works on my machine.

You might want to start Sketch from a Terminal like this:

    /Applications/Sketch.app/Contents/MacOS/Sketch

This will put its log on the terminal. Maybe there's something in there.

**Comment by sevenseacat** [comment]
I'm using a super-old version of Sketch (53.2 😅) and I also get a crash when attempting to resize.

```
2023-01-03 12:45:09.641 Sketch[16629:30753965] Error: An Obj-C exception occurred.
stack: @[native code]
f@/Users/rebecca/Library/Application Support/com.bohemiancoding.sketch3/Plugins/units.sketchplugin/Contents/Sketch/__commands_resize.js:1:6609
@/Users/rebecca/Library/Application Support/com.bohemiancoding.sketch3/Plugins/units.sketchplugin/Contents/Sketch/__commands_resize.js:1:33763
__skpm_run@/Users/rebecca/Library/Application Support/com.bohemiancoding.sketch3/Plugins/units.sketchplugin/Contents/Sketch/__commands_resize.js:1:35399
__skpm_run@[native code]
nativeException: No structure encoding found for CGRect
```

**Comment by dploeger** [comment]
I think, it simply doesn't work with too old versions of Sketch. :)

But nonetheless, I will have to deprecate this plugin as I'm not using Sketch anymore.
