### ISSUE TITLE
Close unexpected

### ISSUE THREAD

**Issue by palamago** [dploeger/sketch-plugin-units#4]
It looks like a nice idea but for Sketch version 53.2 close unexpected when tried to use your plugin (resize option).

Thanks!

**Comment by palamago** [comment]
Update: The plugin crashed when default value is empty. Otherwise it works ok.

**Comment by dploeger** [comment]
Hm. I can not reproduce that. Are you using version v2.0.0-rc.2? What do you mean by "default value is empty"? Is it set to "none"?
