### ISSUE TITLE
units.sketchplugin file is missing from the repository

### ISSUE THREAD

**Issue by Chainzee** [dploeger/sketch-plugin-units#6]

**Comment by dploeger** [comment]
I'm sorry, this issue must've skipped me. Could you please elaborate on what is missing where, if the issue still exists? Thanks.

**Comment by dploeger** [comment]
And if so, please check out [version 2.0.0-rc3](https://github.com/dploeger/sketch-plugin-units/releases/tag/v2.0.0-rc.3) first

**Comment by Chainzee** [comment]
Hi,
The link that you gave me works like a charm (contains just the
units.sketchplugin file) and the tool does the job - Perfect, big thanks!
But the main github site just doesn't have that file - see attachment:


[image: Screenshot 2019-10-18 at 10.23.20.png]

**Comment by dploeger** [comment]
Um, the screenshot didn't come through.

**Comment by Chainzee** [comment]
[image: image.png]

**Comment by dploeger** [comment]
Hm. I think, it doesn't work by email. The image still is gone. 😄

**Comment by Chainzee** [comment]
Try the link then:
https://drive.google.com/open?id=1zcANLWnnn8PfiTMJZzZSh-PpYIspxXjY

;)

**Comment by dploeger** [comment]
Ohhh, now I see. No, the file is a build artifact that is not in the repository. That's why it says "Download the plugin zip file from the releases page" right before that. 😆

**Comment by Chainzee** [comment]
Yup, that's why it's hard to find it at once ;)
