### ISSUE TITLE
Sketch is crashing when using Units plugin

### ISSUE THREAD

**Issue by johnyqi** [dploeger/sketch-plugin-units#7]
I'm not able to get the settings window with Units plugin, and only option that works is the one which shows the current size. It also crashed Sketch several times. It worked fine before, so I'm not sure whether one of the Sketch upgrades broke the plugin.

**Comment by dploeger** [comment]
What version of Sketch are you running?

Hmm. Other plugins shouldn’t actually break another plugin.

**Comment by dploeger** [comment]
(And thanks for opening the issue here. :) )

**Comment by johnyqi** [comment]
I have the latest version of Sketch. Basically, if I click Resize, nothing happens, if I click Settings, Sketch crashes.

I'm attaching the crash log from Sketch, maybe you can see something there.

[Sketch crash.pdf](https://github.com/dploeger/sketch-plugin-units/files/3735328/Sketch.crash.pdf)

**Comment by dploeger** [comment]
Hm. I can't reproduce that with Sketch Version 59 (86127) here. Could you please try version [2.0.0-rc3](https://github.com/dploeger/sketch-plugin-units/releases/tag/v2.0.0-rc.3)?

**Comment by johnyqi** [comment]
it's not working, I deleted the old one and installed rc3 but same problems.

Could it be that Catalina OS is causing issues? I made an upgrade just a few days ago, and since then I noticed the problem.

**Comment by dploeger** [comment]
Oh, that could be. I haven't updated yet, so I'll check it out once I did.

**Comment by dploeger** [comment]
I finally found the time to update to Catalina and could fix the plugin by simply updating skpm-module-web-view.

Please check out [v2.0.0-rc4](https://github.com/dploeger/sketch-plugin-units/releases/tag/v2.0.0-rc.4).

**Comment by johnyqi** [comment]
That worked, thank you!

I love this plugin, I find it really hard to prepare data for print without it, I'm really glad that it works again.

cheers!

Johny

**Comment by dploeger** [comment]
Great. Glad that you like it.
