### ISSUE TITLE
No units.sketchplugin file

### ISSUE THREAD

**Issue by mileshillier** [dploeger/sketch-plugin-units#8]
Instructions say to click on and open units.sketchplugin. This file is missing

**Comment by dploeger** [comment]
Did you download the plugin zip from the releases page? (The entry where it says "To install: download this file, unzip and double click on the .sketchplugin"?)

**Comment by mileshillier** [comment]
I didn’t before. I have never had to do that with other plugins. Interesting that it is in a separate package. 

I added it and the plugin was installed but there are no measurement options in the drop down. I might have missed another download or file to install, merge, or something. I will try again.

**Comment by dploeger** [comment]
What package did you download? There shouldn't be "another package", just that one. 😄

**Comment by dploeger** [comment]
I'm closing this because no answer came
